rescue all exceptions at middleware level only, when set in config to do this.
RenoFi/rack-graphql pull request #101
Opened 2021-01-13 10:08 UTC by xiazek

## Description

I would like to propose an option for the application which is using the middleware, to choose if it wants to have `StandardError` be rescued or i.e. to handle Exception on the application's side.

## Motivation and Context

It would give more freedom to the services using it on how to rescue Exceptions.

## How Has This Been Tested?

rspec

2021-01-13 14:34 UTC, knapo requested changes
Can you make it as `RackGraphql::Application` option, so it can be used directly too vs global option only:

```
run RackGraphql::Application.call(
  ....
  catch_all_exceptions: true
)
```

2021-01-13 14:34 UTC, knapo commented on lib/rack_graphql.rb
> +    attr_writer :log_exception_backtrace, :rescue_exceptions_with_500_json
I'd name it `catch_all_exceptions`

2021-01-14 12:25 UTC, knapo reviewed
I think we should keep the current behaviour, since it's following the graphql spec and only implement the ability to change it, if some users really needs it.  I added https://github.com/RenoFi/rack-graphql/pull/103.

2021-01-14 13:08 UTC, xiazek commented
Thanks for review. I think depending on needs either:
 - #103 (when someone wants to catch exception and handle response on their own)
 - or my other attempt #102:  when someone wants to include error catching middleware (i.e. `Rack::Raven` etc)
 are better.
I'm closing this one.

2021-01-14 13:08 UTC, closed without merging