allow passing root_path_response_builder
RenoFi/rack-graphql pull request #109
Opened 2021-03-23 17:25 UTC by xiazek

## Description

 - allow passing `root_path_response_builder` similarly to `health_response_builder`
 - backward compatible with default to `RackGraphql::HealthResponseBuilder`

## Motivation and Context

Allow to skip or overwrite `map '/'`, while still keeping `/health` without too much custom settings.

2021-03-23 18:39 UTC, knapo requested changes
I think that having a root path setup by default is nice, as most of GQL services doesn't implements any functionality on root path. Also, such change breaks current implementation pretty significantly and except from users to on gem upgrade. 

I'd make it more backwards compatible and only add an option to skip root path setup, so if someone doesn't want it or want to set it up on his/her own 
e.g. `health_on_root_path` option which is `true` by default.

2021-03-23 20:38 UTC, xiazek commented
> I think that having a root path setup by default is nice, as most of GQL services doesn't implements any functionality on root path. Also, such change breaks current implementation pretty significantly and except from users to on gem upgrade.
> 

hmm... the default argument value `root_path_response_builder: RackGraphql::HealthResponseBuilder,` makes it working exactly the same, without any changes required after update. What does it break in your opinion ?

Any behaviour would change only after passing `root_path_response_builder`.

> I'd make it more backwards compatible and only add an option to skip root path setup, so if someone doesn't want it or want to set it up on his/her own
> e.g. `health_on_root_path` option which is `true` by default.

Such option is fine for me too. I'll push an update later. 👍

2021-03-24 06:40 UTC, knapo commented
> hmm... the default argument value root_path_response_builder: RackGraphql::HealthResponseBuilder, makes it working exactly the same, without any changes required after update. What does it break in your opinion ?

huh, my bad, thought it's nil by default 🤦

2021-03-24 06:46 UTC, xiazek commented
> > hmm... the default argument value root_path_response_builder: RackGraphql::HealthResponseBuilder, makes it working exactly the same, without any changes required after update. What does it break in your opinion ?
> 
> huh, my bad, thought it's nil by default 🤦

No problem. Anyway. I like the version:

> [..] e.g. health_on_root_path option which is true by default.

I'll push an update later.

2021-03-24 07:48 UTC, xiazek commented
Updated and added example to README:

https://github.com/RenoFi/rack-graphql/pull/109/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R32

2021-03-24 10:28 UTC, knapo approved these changes

2021-03-24 10:28 UTC, merged